In [1]:
from pdf2image import convert_from_path

In [2]:
images = convert_from_path('test.pdf')

In [3]:
!mkdir pages

In [4]:
for i in range(len(images)):
  images[i].save('pages/page'+str(i)+'.jpg','JPEG')

In [5]:
import ultralytics

In [9]:
import cv2
from ultralytics import YOLO

try:
    # Load the image
    image = cv2.imread("pages\page0.jpg")
    if image is None:
        raise Exception("Error: Unable to read the image.")
    image = image[..., ::-1]

    # Load the YOLO model
    model = YOLO('best.pt')

    # Perform prediction and get results
    results = model.predict(source=image, save=False , conf=0.5 )

    # Access the bounding box coordinates for each detected table
    if len(results) > 0:
        first_result = results[0]  # Assuming the first item in the list contains the results
        bounding_boxes = first_result.boxes.xyxy
        print(bounding_boxes)
    else:
        print("No tables detected.")

except Exception as e:
    print(str(e))


0: 640x512 1 Table, 122.0ms
Speed: 42.0ms preprocess, 122.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 512)
tensor([[ 138.9527,  200.2440, 1543.9772,  547.2715]])


In [10]:
for l in bounding_boxes:
  x_1 = int(l[0])
  y_1 = int(l[1])
  x_2 = int(l[2])
  y_2 = int(l[3])

In [11]:
im = cv2.imread('pages\page0.jpg')

In [12]:
cv2.imwrite('ext_im.jpg',im[y_1:y_2,x_1:x_2])

True

In [13]:
from paddleocr import PaddleOCR

In [14]:
ocr = PaddleOCR(lang = 'en')
image_path = 'ext_im.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)
print(output)


download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to C:\Users\ASUS/.paddleocr/whl\det\en\en_PP-OCRv3_det_infer\en_PP-OCRv3_det_infer.tar


100%|██████████| 4.00M/4.00M [00:03<00:00, 1.12MiB/s]


download https://paddleocr.bj.bcebos.com/PP-OCRv4/english/en_PP-OCRv4_rec_infer.tar to C:\Users\ASUS/.paddleocr/whl\rec\en\en_PP-OCRv4_rec_infer\en_PP-OCRv4_rec_infer.tar


100%|██████████| 10.2M/10.2M [00:13<00:00, 751kiB/s] 


download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to C:\Users\ASUS/.paddleocr/whl\cls\ch_ppocr_mobile_v2.0_cls_infer\ch_ppocr_mobile_v2.0_cls_infer.tar


100%|██████████| 2.19M/2.19M [00:04<00:00, 497kiB/s] 

[2024/01/18 02:29:37] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='C:\\Users\\ASUS/.paddleocr/whl\\det\\en\\en_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\ASUS/.paddleocr/whl\\rec\\en\\en_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_lengt

[2024/01/18 02:29:39] ppocr WARNING: Since the angle classifier is not initialized, it will not be used during the forward process
[2024/01/18 02:29:40] ppocr DEBUG: dt_boxes num : 56, elapsed : 0.6954443454742432
[2024/01/18 02:30:06] ppocr DEBUG: rec_res num  : 56, elapsed : 26.1377112865448
[[[[[57.0, 8.0], [126.0, 8.0], [126.0, 36.0], [57.0, 36.0]], ('DATE', 0.9985253214836121)], [[[186.0, 11.0], [395.0, 11.0], [395.0, 33.0], [186.0, 33.0]], ('TRANSACTIONID', 0.9969203472137451)], [[[559.0, 8.0], [642.0, 8.0], [642.0, 36.0], [559.0, 36.0]], ('MODE', 0.998503565788269)], [[[803.0, 9.0], [978.0, 9.0], [978.0, 31.0], [803.0, 31.0]], ('ACCOUNTNO', 0.9772573113441467)], [[[1010.0, 8.0], [1109.0, 8.0], [1109.0, 36.0], [1010.0, 36.0]], ('STATUS', 0.9976963400840759)], [[[1128.0, 11.0], [1250.0, 11.0], [1250.0, 33.0], [1128.0, 33.0]], ('AMOUNT', 0.996489942073822)], [[[1278.0, 11.0], [1390.0, 11.0], [1390.0, 33.0], [1278.0, 33.0]], ('BALANCE', 0.9975854158401489)], [[[23.0, 48.0], [158.0, 

In [15]:
boxes = [line[0] for sublist in output for line in sublist]
texts = [line[1][0] for sublist in output for line in sublist]

# If you want probabilities as well, you can do this:
probabilities = [line[1][1] for sublist in output for line in sublist]

In [16]:
print(boxes)

[[[57.0, 8.0], [126.0, 8.0], [126.0, 36.0], [57.0, 36.0]], [[186.0, 11.0], [395.0, 11.0], [395.0, 33.0], [186.0, 33.0]], [[559.0, 8.0], [642.0, 8.0], [642.0, 36.0], [559.0, 36.0]], [[803.0, 9.0], [978.0, 9.0], [978.0, 31.0], [803.0, 31.0]], [[1010.0, 8.0], [1109.0, 8.0], [1109.0, 36.0], [1010.0, 36.0]], [[1128.0, 11.0], [1250.0, 11.0], [1250.0, 33.0], [1128.0, 33.0]], [[1278.0, 11.0], [1390.0, 11.0], [1390.0, 33.0], [1278.0, 33.0]], [[23.0, 48.0], [158.0, 48.0], [158.0, 76.0], [23.0, 76.0]], [[258.0, 46.0], [323.0, 46.0], [323.0, 76.0], [258.0, 76.0]], [[438.0, 50.0], [760.0, 50.0], [760.0, 71.0], [438.0, 71.0]], [[814.0, 50.0], [967.0, 50.0], [967.0, 71.0], [814.0, 71.0]], [[1042.0, 46.0], [1077.0, 46.0], [1077.0, 79.0], [1042.0, 79.0]], [[1149.0, 48.0], [1231.0, 48.0], [1231.0, 76.0], [1149.0, 76.0]], [[1294.0, 48.0], [1374.0, 48.0], [1374.0, 76.0], [1294.0, 76.0]], [[23.0, 88.0], [158.0, 88.0], [158.0, 116.0], [23.0, 116.0]], [[258.0, 87.0], [325.0, 87.0], [325.0, 116.0], [258.0, 11

In [17]:

image_boxes = image_cv.copy()


In [18]:
for box,text in zip(boxes,texts):
    cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])) , (0,0,255),1)
    cv2.putText(image_boxes , text,(int(box[0][0]), int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)
cv2.imwrite('detections.jpg' , image_boxes)

True

In [19]:
im2 = image_cv.copy()

In [20]:
horiz_boxes = []
vert_boxes = []
 
for box in boxes:
    x_h, x_v = 0, int(box[0][0])
    y_h, y_v = int(box[0][1]), 0

    width_h, width_v = image_width, int(box[2][0]) - int(box[0][0])
    height_h, height_v = int(box[2][1]) - int(box[0][1]), image_height
    horiz_boxes.append([x_h, y_h, x_h + width_h, y_h + height_h])
    vert_boxes.append([x_v, y_v, x_v + width_v, y_v + height_v])

    cv2.rectangle(im2,(x_h, y_h),(x_h + width_h ,y_h+height_h),(255,255,0),1)
    cv2.rectangle(im2,(x_v, y_v),(x_v + width_v ,y_v+height_v),(0,255,0),1)



In [21]:
cv2.imwrite('horiz_vert.jpg',im2)

True

In [22]:
import tensorflow as tf

[2024-01-18 02:30:37,620] [ WARNING] module_wrapper.py:149 - From d:\rajisthan hack\Kavach_2023\myenvp\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.



In [23]:
import numpy as np

In [24]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size= 1000,
    iou_threshold= 0.1,
    score_threshold = float('-inf'),
    name = None
)

In [25]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 0  8 19 22 29 41 47 52]


In [26]:
im_nms = image_cv.copy()

In [27]:
for val in horiz_lines:
    cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])) , (0,0,255),1)
    

In [28]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [29]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size= 1000,
    iou_threshold= 0.1,
    score_threshold = float('-inf'),
    name = None
)

In [30]:
print(vert_out)

tf.Tensor([41 19 52 22 18  0  2], shape=(7,), dtype=int32)


In [31]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[ 0  2 18 19 22 41 52]


In [32]:
for val in vert_lines:
    cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])) , (255,0,0),1)
    

In [33]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [34]:
out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(8, 7)
[['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', '']]


In [35]:
unordered_boxes = []
for i in vert_lines:
    print(vert_boxes[i])
    unordered_boxes.append(vert_boxes[i][0])

[57, 0, 126, 347]
[559, 0, 642, 347]
[1041, 0, 1079, 347]
[1149, 0, 1231, 347]
[258, 0, 325, 347]
[1292, 0, 1374, 347]
[812, 0, 970, 347]


In [36]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[0 4 1 6 2 3 5]


In [37]:
def intersection(box_1 , box_2):
    return [box_2[0], box_1[1] , box_2[2] , box_1[3] ]

In [38]:
def iou(box_1 , box_2 ,):
  x_1 = max(box_1[0],box_2[0])
  y_1 = max(box_1[1],box_2[1])
  x_2 = min(box_1[2],box_2[2])
  y_2 = min(box_1[3],box_2[3])
  
  inter = abs(max((x_2 - x_1, 0)) * max ((y_2 - y_1), 0))
  if inter == 0 :
    return 0
  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))
  return inter / float (box_1_area + box_2_area - inter)

In [39]:
for i in range(len(horiz_lines)):
    for j in range(len(vert_lines)):
        resultant = intersection(horiz_boxes[horiz_lines[i]],vert_boxes[vert_lines[ordered_boxes[j]]])

        for b in range (len(boxes)):
            the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
            if(iou(resultant , the_box)>0.1):
                out_array[i][j] = texts[b]
        print(resultant)

[57, 8, 126, 36]
[258, 8, 325, 36]
[559, 8, 642, 36]
[812, 8, 970, 36]
[1041, 8, 1079, 36]
[1149, 8, 1231, 36]
[1292, 8, 1374, 36]
[57, 46, 126, 76]
[258, 46, 325, 76]
[559, 46, 642, 76]
[812, 46, 970, 76]
[1041, 46, 1079, 76]
[1149, 46, 1231, 76]
[1292, 46, 1374, 76]
[57, 88, 126, 116]
[258, 88, 325, 116]
[559, 88, 642, 116]
[812, 88, 970, 116]
[1041, 88, 1079, 116]
[1149, 88, 1231, 116]
[1292, 88, 1374, 116]
[57, 129, 126, 158]
[258, 129, 325, 158]
[559, 129, 642, 158]
[812, 129, 970, 158]
[1041, 129, 1079, 158]
[1149, 129, 1231, 158]
[1292, 129, 1374, 158]
[57, 169, 126, 197]
[258, 169, 325, 197]
[559, 169, 642, 197]
[812, 169, 970, 197]
[1041, 169, 1079, 197]
[1149, 169, 1231, 197]
[1292, 169, 1374, 197]
[57, 209, 126, 237]
[258, 209, 325, 237]
[559, 209, 642, 237]
[812, 209, 970, 237]
[1041, 209, 1079, 237]
[1149, 209, 1231, 237]
[1292, 209, 1374, 237]
[57, 249, 126, 277]
[258, 249, 325, 277]
[559, 249, 642, 277]
[812, 249, 970, 277]
[1041, 249, 1079, 277]
[1149, 249, 1231, 277]
[

In [40]:
out_array

[['DATE', 'TRANSACTIONID', 'MODE', 'ACCOUNTNO', 'STATUS', 'AMOUNT', 'BALANCE'],
 ['7/27/2023',
  '1005',
  'UPI(Transfer from ARYAN)',
  '7940418579',
  'Cr',
  '80000',
  '80000'],
 ['7/27/2023',
  '1006',
  'UPI(Transfer to ABHISHEK)',
  '2497653801',
  'Dr',
  '33000',
  '47000'],
 ['7/27/2023',
  '1007',
  'UPI(Transfer to TEJAS)',
  '2173014683',
  'Dr',
  '5000',
  '42000'],
 ['7/27/2023',
  '1008',
  'UPI(Transfer to RAHUL)',
  '3665537576',
  'Dr',
  '16000',
  '26000'],
 ['7/27/2023',
  '1009',
  'UPI(Transfer to RAJKUMAR)',
  '2842027745',
  'Dr',
  '6700',
  '19300'],
 ['7/27/2023',
  '1010',
  'UPI(Transfer to MUKUND)',
  '7542630333',
  'Dr',
  '5300',
  '14000'],
 ['7/27/2023',
  '1011',
  'UPI(Transfer to ANIL)',
  '1734168306',
  'Dr',
  '14000',
  '0']]

In [41]:
import pandas as pd

In [42]:
pd.DataFrame(out_array).to_csv('sample.csv')